# fly.toml app configuration file generated for mixpanel-testing-app on 2025-05-07T16:55:34+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mixpanel-testing-app'
primary_region = 'bom'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_assigned_fulfillment_orders,read_cart_transforms,read_checkout_branding_settings,read_content,read_customer_events,read_customers,read_delivery_customizations,read_draft_orders,read_fulfillments,read_inventory,read_marketing_events,read_markets,read_merchant_managed_fulfillment_orders,read_online_store_navigation,read_order_edits,read_orders,read_payment_customizations,read_purchase_options,read_third_party_fulfillment_orders,write_customers,write_fulfillments,write_orders,write_pixels'
  SHOPIFY_API_KEY = '1003dfd9518ccce9e0936021b11658f4'
  SHOPIFY_APP_URL = 'https://mixpanel-testing-app.fly.dev'

[processes]
  app = 'node ./dbsetup.js npm run docker-start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
